import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  safeAreaContainer: {flex: 1, backgroundColor: '#0C365A'},
  container: {flex: 1},
  topContainer: {flex: 1, paddingHorizontal: 24},
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 24,
  },
  headerTextStyle: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'left',
  },
  logoStyle: {width: 25, height: 25},
  availableBalanceStyle: {
    fontSize: 14,
    textAlign: 'left',
    color: '#ffffff',
    lineHeight: 16,
    paddingBottom: 15,
  },
  availableBalanceContainer: {flexDirection: 'row', alignItems: 'center'},
  currencyContainer: {
    width: 40,
    height: 22,
    borderRadius: 4,
    backgroundColor: '#01D167',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  currencyTextStyle: {
    fontSize: 12,
    color: '#ffffff',
    lineHeight: 16,
    fontWeight: 'bold',
  },
  availableBalanceNumberStyle: {
    fontSize: 24,
    textAlign: 'left',
    color: '#ffffff',
    fontWeight: 'bold',
  },
  bottomContainer: {
    flex: 2,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    zIndex: 1000,
  },
  cardContainer: {marginTop: '-28%', marginBottom: 32},
  cardContainerChild: {
    width: 151,
    height: 44,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    paddingHorizontal: 12,
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginBottom: -10
  },
  eyeIconContainer: {width: 16, height: 16, marginBottom: 10, marginRight: 5},
  showCardNumberStyle: {
    fontSize: 12,
    textAlign: 'left',
    color: '#01D167',
    lineHeight: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  cardLogoContainer: {
    height: 220,
    backgroundColor: '#01D167',
    borderRadius: 10,
    paddingVertical: 24,
    paddingHorizontal: 24,
  },
  cardLogoStyle: {
    width: 74,
    height: 21,
    alignSelf: 'flex-end',
    marginBottom: 24,
  },
  nameTextStyle: {
    fontSize: 22,
    textAlign: 'left',
    color: '#FFFFFF',
    lineHeight: 20,
    fontWeight: 'bold',
    marginBottom: 24,
  },
  cardNumberContainer: {flexDirection: 'row', marginBottom: 19},
  cardNumberTextStyle: {
    fontSize: 14,
    textAlign: 'left',
    color: '#FFFFFF',
    lineHeight: 19,
    fontWeight: '500',
    marginRight: 24,
  },
  validityStyle: {flexDirection: 'row'},
  validityTextStyle: {
    fontSize: 13,
    textAlign: 'left',
    color: '#FFFFFF',
    lineHeight: 18,
    fontWeight: '500',
    marginRight: 32,
  },
  cvvTextStyle: {
    fontSize: 13,
    color: '#FFFFFF',
    lineHeight: 18,
    fontWeight: '500',
  },
  visaLogoStyle: {width: 74, height: 21, alignSelf: 'flex-end'},
  listitemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 41,
  },
  listItemImageStyle: {width: 32, height: 32, marginRight: 12},
  listItemTextContainer: {
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  listItemTitleText: {
    fontSize: 14,
    color: '#25345F',
    lineHeight: 14,
    fontWeight: '400',
    marginBottom: 4,
  },
  listItemSubTitleText: {
    fontSize: 13,
    color: '#222222',
    lineHeight: 12,
    opacity: 0.4,
  },
  switchContainer: {position: 'absolute', right: 0, alignItems: 'center'},
});
