import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  safeAreaContainer: {flex: 1, backgroundColor: '#0C365A'},
  container: {flex: 1},
  headerContainer: {
    height: 56,
    flexDirection: 'row',
    paddingHorizontal: 24,
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  headerIconStyle: {width: 25, height: 25},
  titleTextStyle: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'left',
    marginBottom: 40,
    paddingHorizontal: 24,
  },
  bottomContainer: {
    flex: 1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
  },
  spendingLimitContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 33,
    paddingBottom: 19,
  },
  spendingLimitIconStyle: {width: 16, height: 16, marginRight: 12},
  spendingLimitMsgStyle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '400',
    color: '#222222',
    textAlign: 'left',
  },
  spendingLimitAmountContainer: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#e6e6e6',
    marginBottom: 12,
    alignItems: 'center'
  },
  currencyBoxStyle: {
    width: 40,
    height: 22,
    borderRadius: 4,
    backgroundColor: '#01D167',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  currencyTextStyle: {
    fontSize: 12,
    color: '#ffffff',
    lineHeight: 16,
    fontWeight: 'bold',
  },
  noteTextStyle: {
    fontSize: 13,
    color: '#22222266',
    lineHeight: 18,
    marginBottom: 32,
  },
  amountListContainer: {flexDirection: 'row', justifyContent: 'space-between'},
  amountListItemStyle: {
    width: '30%',
    height: 40,
    backgroundColor: '#d3f8e2',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  amountTextStyle: {
    fontSize: 12,
    color: '#01D167',
    lineHeight: 16,
    fontWeight: '500',
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 24,
    left: 33,
    right: 33,
    borderRadius: 30,
    backgroundColor: '#EEEEEE',
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonTextStyle: {
    fontSize: 16,
    color: '#FFFFFF',
    lineHeight: 20,
    fontWeight: '500',
  },
});
